### ISSUE TITLE
Export ML Model (2hr/10hr)

### ISSUE THREAD

**Issue by baxterhc** [expectedValueVU/CSX278#19]

**Comment by hunterbaxter** [comment]
This step requires a trained model to be exported. Originally, we thought we would use a .pkl file, but this is going to be depreciated by xgboost, so we will be using their in-house solution (I think).

**Comment by hunterbaxter** [comment]
Also, this step requires knowledge on how we intend on using this model with our front end. Ideally, we are not entirely exporting the model to a JS framework, but we may have to do that.
